version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.10.3
    - image: circleci/mongo:4.0.0

    working_directory: /go/src/github.com/lab259/go-migration-tenant
    steps:
    - checkout

    - run:
        name: Install dockerize
        command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
        environment:
          DOCKERIZE_VERSION: v0.3.0

    - run:
        name: Wait for Mongo
        command: dockerize -wait tcp://localhost:27017 -timeout 1m

    - run:
        name: Install Dep
        command: |
          go get -u github.com/tools/godep

    - run:
        name: Install Ginkgo
        command: |
          go get -u github.com/onsi/ginkgo/ginkgo

    - run:
        name: Get dependencies
        command: |
          make dep-ensure

    - run:
        name: Run tests
        command: |
          make coverage-ci

    - run: bash <(curl -s https://codecov.io/bash)